### ISSUE TITLE
Why are you using Dropbox downloads when this is on Github?

### ISSUE THREAD

**Issue by HelveticaToast** [edwardscamera/MinecraftServerShell#2]
Just upload the ZIP directly to Github.

**Comment by WashingtonARamos** [comment]
As a more helpful feedback, Github has a feature called [Releases](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-releases) which lets you upload production binaries of your software. You should use it so that users can download binaries directly from Github and not thid-party websites.

**Comment by edwardscamera** [comment]
Electron projects have two forms, uncompiled and compiled. Uncompiled has source code and everything needed to build the project, and the compiled version is just program files, including an EXE. I would upload the compiled feature to Releases, but it seems files there have a 10MB limit. The compiled project is 110MB. If I am misinformed or there is another way around this limit, please tell me! I originally wanted to put it as a release file but couldn't because of the limit. Thank you

**Comment by edwardscamera** [comment]
Nevermind! I guess I was uploading the .zip file in the wrong place. It is now in the release. Thank you for your report (:
